import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "../components/navbar"; // Ensure the path is correct
import TransitionProvider from "@/components/transitionProvider"; // Ensure path correctness

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Vinay Portfolio App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Wrap your children in TransitionProvider to ensure animations */}
        <TransitionProvider>
          {children}
        </TransitionProvider>
      </body>
    </html>
  );
}
